# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'enemyeditor.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QMainWindow,
    QPlainTextEdit, QPushButton, QSizePolicy, QTabWidget,
    QWidget)

class Ui_EnemyEditor(object):
    def setupUi(self, EnemyEditor):
        if not EnemyEditor.objectName():
            EnemyEditor.setObjectName(u"EnemyEditor")
        EnemyEditor.resize(470, 634)
        EnemyEditor.setMinimumSize(QSize(470, 634))
        EnemyEditor.setMaximumSize(QSize(470, 634))
        self.MainUI = QWidget(EnemyEditor)
        self.MainUI.setObjectName(u"MainUI")
        self.tabWidget = QTabWidget(self.MainUI)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 451, 581))
        self.EnemyEdit = QWidget()
        self.EnemyEdit.setObjectName(u"EnemyEdit")
        self.EnemiesList = QListWidget(self.EnemyEdit)
        self.EnemiesList.setObjectName(u"EnemiesList")
        self.EnemiesList.setGeometry(QRect(10, 20, 211, 471))
        self.EnemiesList.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.EnemiesList.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.EnemyStats = QGroupBox(self.EnemyEdit)
        self.EnemyStats.setObjectName(u"EnemyStats")
        self.EnemyStats.setGeometry(QRect(230, 10, 211, 531))
        self.EnemyID = QLabel(self.EnemyStats)
        self.EnemyID.setObjectName(u"EnemyID")
        self.EnemyID.setGeometry(QRect(10, 60, 21, 16))
        self.EnemyName = QLabel(self.EnemyStats)
        self.EnemyName.setObjectName(u"EnemyName")
        self.EnemyName.setGeometry(QRect(10, 90, 49, 16))
        self.EnemyGID = QLabel(self.EnemyStats)
        self.EnemyGID.setObjectName(u"EnemyGID")
        self.EnemyGID.setGeometry(QRect(10, 190, 21, 16))
        self.EnemyIDVal = QLineEdit(self.EnemyStats)
        self.EnemyIDVal.setObjectName(u"EnemyIDVal")
        self.EnemyIDVal.setGeometry(QRect(80, 60, 111, 22))
        self.EnemyNameVal = QLineEdit(self.EnemyStats)
        self.EnemyNameVal.setObjectName(u"EnemyNameVal")
        self.EnemyNameVal.setGeometry(QRect(80, 90, 111, 22))
        self.EnemyGIDVal = QLineEdit(self.EnemyStats)
        self.EnemyGIDVal.setObjectName(u"EnemyGIDVal")
        self.EnemyGIDVal.setGeometry(QRect(50, 190, 51, 22))
        self.EnemyBID = QLabel(self.EnemyStats)
        self.EnemyBID.setObjectName(u"EnemyBID")
        self.EnemyBID.setGeometry(QRect(10, 120, 21, 20))
        self.EnemyBIDVal = QLineEdit(self.EnemyStats)
        self.EnemyBIDVal.setObjectName(u"EnemyBIDVal")
        self.EnemyBIDVal.setGeometry(QRect(80, 120, 111, 22))
        self.EnemyHP = QLabel(self.EnemyStats)
        self.EnemyHP.setObjectName(u"EnemyHP")
        self.EnemyHP.setGeometry(QRect(10, 260, 21, 16))
        self.EnemySTR = QLabel(self.EnemyStats)
        self.EnemySTR.setObjectName(u"EnemySTR")
        self.EnemySTR.setGeometry(QRect(110, 260, 21, 16))
        self.EnemySPD = QLabel(self.EnemyStats)
        self.EnemySPD.setObjectName(u"EnemySPD")
        self.EnemySPD.setGeometry(QRect(10, 290, 31, 16))
        self.EnemyATK = QLabel(self.EnemyStats)
        self.EnemyATK.setObjectName(u"EnemyATK")
        self.EnemyATK.setGeometry(QRect(110, 290, 21, 16))
        self.EnemyDEF = QLabel(self.EnemyStats)
        self.EnemyDEF.setObjectName(u"EnemyDEF")
        self.EnemyDEF.setGeometry(QRect(10, 320, 21, 16))
        self.EnemyAPT = QLabel(self.EnemyStats)
        self.EnemyAPT.setObjectName(u"EnemyAPT")
        self.EnemyAPT.setGeometry(QRect(110, 320, 21, 16))
        self.EnemyHPVal = QLineEdit(self.EnemyStats)
        self.EnemyHPVal.setObjectName(u"EnemyHPVal")
        self.EnemyHPVal.setGeometry(QRect(50, 260, 51, 22))
        self.EnemySTRVal = QLineEdit(self.EnemyStats)
        self.EnemySTRVal.setObjectName(u"EnemySTRVal")
        self.EnemySTRVal.setGeometry(QRect(150, 260, 51, 22))
        self.EnemySPDVal = QLineEdit(self.EnemyStats)
        self.EnemySPDVal.setObjectName(u"EnemySPDVal")
        self.EnemySPDVal.setGeometry(QRect(50, 290, 51, 22))
        self.EnemyATKVal = QLineEdit(self.EnemyStats)
        self.EnemyATKVal.setObjectName(u"EnemyATKVal")
        self.EnemyATKVal.setGeometry(QRect(150, 290, 51, 22))
        self.EnemyDEFVal = QLineEdit(self.EnemyStats)
        self.EnemyDEFVal.setObjectName(u"EnemyDEFVal")
        self.EnemyDEFVal.setGeometry(QRect(50, 320, 51, 22))
        self.EnemyAPTVal = QLineEdit(self.EnemyStats)
        self.EnemyAPTVal.setObjectName(u"EnemyAPTVal")
        self.EnemyAPTVal.setGeometry(QRect(150, 320, 51, 22))
        self.EnemyFATK = QLabel(self.EnemyStats)
        self.EnemyFATK.setObjectName(u"EnemyFATK")
        self.EnemyFATK.setGeometry(QRect(10, 350, 31, 16))
        self.EnemyIATK = QLabel(self.EnemyStats)
        self.EnemyIATK.setObjectName(u"EnemyIATK")
        self.EnemyIATK.setGeometry(QRect(10, 380, 31, 16))
        self.EnemyLATK = QLabel(self.EnemyStats)
        self.EnemyLATK.setObjectName(u"EnemyLATK")
        self.EnemyLATK.setGeometry(QRect(10, 410, 31, 16))
        self.EnemyFATKVal = QLineEdit(self.EnemyStats)
        self.EnemyFATKVal.setObjectName(u"EnemyFATKVal")
        self.EnemyFATKVal.setGeometry(QRect(50, 350, 51, 22))
        self.EnemyLATKVal = QLineEdit(self.EnemyStats)
        self.EnemyLATKVal.setObjectName(u"EnemyLATKVal")
        self.EnemyLATKVal.setGeometry(QRect(50, 410, 51, 22))
        self.EnemyIATKVal = QLineEdit(self.EnemyStats)
        self.EnemyIATKVal.setObjectName(u"EnemyIATKVal")
        self.EnemyIATKVal.setGeometry(QRect(50, 380, 51, 22))
        self.EnemyIDEF = QLabel(self.EnemyStats)
        self.EnemyIDEF.setObjectName(u"EnemyIDEF")
        self.EnemyIDEF.setGeometry(QRect(110, 380, 31, 16))
        self.EnemyFDEFVal = QLineEdit(self.EnemyStats)
        self.EnemyFDEFVal.setObjectName(u"EnemyFDEFVal")
        self.EnemyFDEFVal.setGeometry(QRect(150, 350, 51, 22))
        self.EnemyIDEFVal = QLineEdit(self.EnemyStats)
        self.EnemyIDEFVal.setObjectName(u"EnemyIDEFVal")
        self.EnemyIDEFVal.setGeometry(QRect(150, 380, 51, 22))
        self.EnemyLDEF = QLabel(self.EnemyStats)
        self.EnemyLDEF.setObjectName(u"EnemyLDEF")
        self.EnemyLDEF.setGeometry(QRect(110, 410, 31, 16))
        self.EnemyLDEFVal = QLineEdit(self.EnemyStats)
        self.EnemyLDEFVal.setObjectName(u"EnemyLDEFVal")
        self.EnemyLDEFVal.setGeometry(QRect(150, 410, 51, 22))
        self.EnemyFDEF = QLabel(self.EnemyStats)
        self.EnemyFDEF.setObjectName(u"EnemyFDEF")
        self.EnemyFDEF.setGeometry(QRect(110, 350, 31, 16))
        self.EnemyILevelVal = QLineEdit(self.EnemyStats)
        self.EnemyILevelVal.setObjectName(u"EnemyILevelVal")
        self.EnemyILevelVal.setGeometry(QRect(50, 470, 51, 22))
        self.EnemyLevel = QLabel(self.EnemyStats)
        self.EnemyLevel.setObjectName(u"EnemyLevel")
        self.EnemyLevel.setGeometry(QRect(110, 440, 41, 16))
        self.EnemyRarity = QLabel(self.EnemyStats)
        self.EnemyRarity.setObjectName(u"EnemyRarity")
        self.EnemyRarity.setGeometry(QRect(110, 470, 31, 20))
        self.EnemyExp = QLabel(self.EnemyStats)
        self.EnemyExp.setObjectName(u"EnemyExp")
        self.EnemyExp.setGeometry(QRect(10, 440, 61, 16))
        self.EnemyRarityVal = QLineEdit(self.EnemyStats)
        self.EnemyRarityVal.setObjectName(u"EnemyRarityVal")
        self.EnemyRarityVal.setGeometry(QRect(150, 470, 51, 22))
        self.EnemyLevelVal = QLineEdit(self.EnemyStats)
        self.EnemyLevelVal.setObjectName(u"EnemyLevelVal")
        self.EnemyLevelVal.setGeometry(QRect(150, 440, 51, 22))
        self.EnemyILevel = QLabel(self.EnemyStats)
        self.EnemyILevel.setObjectName(u"EnemyILevel")
        self.EnemyILevel.setGeometry(QRect(10, 470, 31, 16))
        self.EnemyExpVal = QLineEdit(self.EnemyStats)
        self.EnemyExpVal.setObjectName(u"EnemyExpVal")
        self.EnemyExpVal.setGeometry(QRect(50, 440, 51, 22))
        self.EnemyMaxItemsVal = QLineEdit(self.EnemyStats)
        self.EnemyMaxItemsVal.setObjectName(u"EnemyMaxItemsVal")
        self.EnemyMaxItemsVal.setGeometry(QRect(100, 500, 51, 22))
        self.EnemyMaxItems = QLabel(self.EnemyStats)
        self.EnemyMaxItems.setObjectName(u"EnemyMaxItems")
        self.EnemyMaxItems.setGeometry(QRect(30, 500, 61, 20))
        self.EnemyKeyVal = QLineEdit(self.EnemyStats)
        self.EnemyKeyVal.setObjectName(u"EnemyKeyVal")
        self.EnemyKeyVal.setGeometry(QRect(80, 30, 111, 22))
        self.EnemyKey = QLabel(self.EnemyStats)
        self.EnemyKey.setObjectName(u"EnemyKey")
        self.EnemyKey.setGeometry(QRect(10, 30, 21, 16))
        self.EnemyBitmap = QLabel(self.EnemyStats)
        self.EnemyBitmap.setObjectName(u"EnemyBitmap")
        self.EnemyBitmap.setGeometry(QRect(130, 170, 64, 64))
        self.EnemyBitmap.setAutoFillBackground(True)
        self.EnemyBitmap.setFrameShape(QFrame.Shape.Box)
        self.EnemyAddButton = QPushButton(self.EnemyEdit)
        self.EnemyAddButton.setObjectName(u"EnemyAddButton")
        self.EnemyAddButton.setGeometry(QRect(30, 510, 75, 24))
        self.EnemyDeleteButton = QPushButton(self.EnemyEdit)
        self.EnemyDeleteButton.setObjectName(u"EnemyDeleteButton")
        self.EnemyDeleteButton.setGeometry(QRect(120, 510, 75, 24))
        self.tabWidget.addTab(self.EnemyEdit, "")
        self.BattleSimulator = QWidget()
        self.BattleSimulator.setObjectName(u"BattleSimulator")
        self.PlayerStats = QGroupBox(self.BattleSimulator)
        self.PlayerStats.setObjectName(u"PlayerStats")
        self.PlayerStats.setGeometry(QRect(210, 10, 231, 331))
        self.PlayerHP = QLabel(self.PlayerStats)
        self.PlayerHP.setObjectName(u"PlayerHP")
        self.PlayerHP.setGeometry(QRect(10, 30, 21, 16))
        self.PlayerMaxHP = QLabel(self.PlayerStats)
        self.PlayerMaxHP.setObjectName(u"PlayerMaxHP")
        self.PlayerMaxHP.setGeometry(QRect(110, 30, 41, 16))
        self.PlayerSTR = QLabel(self.PlayerStats)
        self.PlayerSTR.setObjectName(u"PlayerSTR")
        self.PlayerSTR.setGeometry(QRect(10, 60, 21, 16))
        self.PlayerCON = QLabel(self.PlayerStats)
        self.PlayerCON.setObjectName(u"PlayerCON")
        self.PlayerCON.setGeometry(QRect(110, 60, 49, 16))
        self.PlayerDEX = QLabel(self.PlayerStats)
        self.PlayerDEX.setObjectName(u"PlayerDEX")
        self.PlayerDEX.setGeometry(QRect(10, 90, 21, 16))
        self.PlayerATK = QLabel(self.PlayerStats)
        self.PlayerATK.setObjectName(u"PlayerATK")
        self.PlayerATK.setGeometry(QRect(110, 90, 49, 16))
        self.PlayerDEF = QLabel(self.PlayerStats)
        self.PlayerDEF.setObjectName(u"PlayerDEF")
        self.PlayerDEF.setGeometry(QRect(10, 120, 21, 16))
        self.PlayerSPD = QLabel(self.PlayerStats)
        self.PlayerSPD.setObjectName(u"PlayerSPD")
        self.PlayerSPD.setGeometry(QRect(110, 120, 49, 16))
        self.PlayerHPVal = QLineEdit(self.PlayerStats)
        self.PlayerHPVal.setObjectName(u"PlayerHPVal")
        self.PlayerHPVal.setGeometry(QRect(50, 30, 51, 22))
        self.PlayerMaxHPVal = QLineEdit(self.PlayerStats)
        self.PlayerMaxHPVal.setObjectName(u"PlayerMaxHPVal")
        self.PlayerMaxHPVal.setGeometry(QRect(160, 30, 51, 22))
        self.PlayerSTRVal = QLineEdit(self.PlayerStats)
        self.PlayerSTRVal.setObjectName(u"PlayerSTRVal")
        self.PlayerSTRVal.setGeometry(QRect(50, 60, 51, 22))
        self.PlayerDEXVal = QLineEdit(self.PlayerStats)
        self.PlayerDEXVal.setObjectName(u"PlayerDEXVal")
        self.PlayerDEXVal.setGeometry(QRect(50, 90, 51, 22))
        self.PlayerDEFVal = QLineEdit(self.PlayerStats)
        self.PlayerDEFVal.setObjectName(u"PlayerDEFVal")
        self.PlayerDEFVal.setGeometry(QRect(50, 120, 51, 22))
        self.PlayerSPDVal = QLineEdit(self.PlayerStats)
        self.PlayerSPDVal.setObjectName(u"PlayerSPDVal")
        self.PlayerSPDVal.setGeometry(QRect(160, 120, 51, 22))
        self.PlayerATKVal = QLineEdit(self.PlayerStats)
        self.PlayerATKVal.setObjectName(u"PlayerATKVal")
        self.PlayerATKVal.setGeometry(QRect(160, 90, 51, 22))
        self.PlayerCONVal = QLineEdit(self.PlayerStats)
        self.PlayerCONVal.setObjectName(u"PlayerCONVal")
        self.PlayerCONVal.setGeometry(QRect(160, 60, 51, 22))
        self.PlayerLATKVal = QLineEdit(self.PlayerStats)
        self.PlayerLATKVal.setObjectName(u"PlayerLATKVal")
        self.PlayerLATKVal.setGeometry(QRect(50, 210, 51, 22))
        self.PlayerLATK = QLabel(self.PlayerStats)
        self.PlayerLATK.setObjectName(u"PlayerLATK")
        self.PlayerLATK.setGeometry(QRect(10, 210, 31, 16))
        self.PlayerLDEF = QLabel(self.PlayerStats)
        self.PlayerLDEF.setObjectName(u"PlayerLDEF")
        self.PlayerLDEF.setGeometry(QRect(110, 210, 49, 16))
        self.PlayerIDEF = QLabel(self.PlayerStats)
        self.PlayerIDEF.setObjectName(u"PlayerIDEF")
        self.PlayerIDEF.setGeometry(QRect(110, 180, 49, 16))
        self.PlayerIDEFVal = QLineEdit(self.PlayerStats)
        self.PlayerIDEFVal.setObjectName(u"PlayerIDEFVal")
        self.PlayerIDEFVal.setGeometry(QRect(160, 180, 51, 22))
        self.PlayerIATKVal = QLineEdit(self.PlayerStats)
        self.PlayerIATKVal.setObjectName(u"PlayerIATKVal")
        self.PlayerIATKVal.setGeometry(QRect(50, 180, 51, 22))
        self.PlayerFDEF = QLabel(self.PlayerStats)
        self.PlayerFDEF.setObjectName(u"PlayerFDEF")
        self.PlayerFDEF.setGeometry(QRect(110, 150, 49, 16))
        self.PlayerFATK = QLabel(self.PlayerStats)
        self.PlayerFATK.setObjectName(u"PlayerFATK")
        self.PlayerFATK.setGeometry(QRect(10, 150, 31, 16))
        self.PlayerLDEFVal = QLineEdit(self.PlayerStats)
        self.PlayerLDEFVal.setObjectName(u"PlayerLDEFVal")
        self.PlayerLDEFVal.setGeometry(QRect(160, 210, 51, 22))
        self.PlayerFDEFVal = QLineEdit(self.PlayerStats)
        self.PlayerFDEFVal.setObjectName(u"PlayerFDEFVal")
        self.PlayerFDEFVal.setGeometry(QRect(160, 150, 51, 22))
        self.PlayerFATKVal = QLineEdit(self.PlayerStats)
        self.PlayerFATKVal.setObjectName(u"PlayerFATKVal")
        self.PlayerFATKVal.setGeometry(QRect(50, 150, 51, 22))
        self.PlayerIATK = QLabel(self.PlayerStats)
        self.PlayerIATK.setObjectName(u"PlayerIATK")
        self.PlayerIATK.setGeometry(QRect(10, 180, 31, 16))
        self.PlayerBlock = QLabel(self.PlayerStats)
        self.PlayerBlock.setObjectName(u"PlayerBlock")
        self.PlayerBlock.setGeometry(QRect(110, 270, 49, 16))
        self.PlayerIDMGVal = QLineEdit(self.PlayerStats)
        self.PlayerIDMGVal.setObjectName(u"PlayerIDMGVal")
        self.PlayerIDMGVal.setGeometry(QRect(160, 240, 51, 22))
        self.PlayerLDMGVal = QLineEdit(self.PlayerStats)
        self.PlayerLDMGVal.setObjectName(u"PlayerLDMGVal")
        self.PlayerLDMGVal.setGeometry(QRect(50, 270, 51, 22))
        self.PlayerFDMG = QLabel(self.PlayerStats)
        self.PlayerFDMG.setObjectName(u"PlayerFDMG")
        self.PlayerFDMG.setGeometry(QRect(10, 240, 41, 16))
        self.PlayerIDMG = QLabel(self.PlayerStats)
        self.PlayerIDMG.setObjectName(u"PlayerIDMG")
        self.PlayerIDMG.setGeometry(QRect(110, 240, 49, 16))
        self.PlayerBlockVal = QLineEdit(self.PlayerStats)
        self.PlayerBlockVal.setObjectName(u"PlayerBlockVal")
        self.PlayerBlockVal.setGeometry(QRect(160, 270, 51, 22))
        self.PlayerLDMG = QLabel(self.PlayerStats)
        self.PlayerLDMG.setObjectName(u"PlayerLDMG")
        self.PlayerLDMG.setGeometry(QRect(10, 270, 49, 16))
        self.PlayerFDMGVal = QLineEdit(self.PlayerStats)
        self.PlayerFDMGVal.setObjectName(u"PlayerFDMGVal")
        self.PlayerFDMGVal.setGeometry(QRect(50, 240, 51, 22))
        self.PlayerAPT = QLabel(self.PlayerStats)
        self.PlayerAPT.setObjectName(u"PlayerAPT")
        self.PlayerAPT.setGeometry(QRect(60, 300, 49, 16))
        self.PlayerAPTVal = QLineEdit(self.PlayerStats)
        self.PlayerAPTVal.setObjectName(u"PlayerAPTVal")
        self.PlayerAPTVal.setGeometry(QRect(100, 300, 51, 22))
        self.SimEnemiesList = QListWidget(self.BattleSimulator)
        self.SimEnemiesList.setObjectName(u"SimEnemiesList")
        self.SimEnemiesList.setGeometry(QRect(10, 10, 181, 331))
        self.SimEnemiesList.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.SimEnemiesList.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.CombatLog = QGroupBox(self.BattleSimulator)
        self.CombatLog.setObjectName(u"CombatLog")
        self.CombatLog.setGeometry(QRect(10, 380, 421, 161))
        self.CombatLogOutput = QPlainTextEdit(self.CombatLog)
        self.CombatLogOutput.setObjectName(u"CombatLogOutput")
        self.CombatLogOutput.setGeometry(QRect(10, 20, 401, 131))
        self.CombatLogOutput.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.PlayerAttack = QPushButton(self.BattleSimulator)
        self.PlayerAttack.setObjectName(u"PlayerAttack")
        self.PlayerAttack.setGeometry(QRect(360, 350, 75, 24))
        self.PlayerResetHP = QPushButton(self.BattleSimulator)
        self.PlayerResetHP.setObjectName(u"PlayerResetHP")
        self.PlayerResetHP.setGeometry(QRect(210, 350, 75, 24))
        self.tabWidget.addTab(self.BattleSimulator, "")
        self.SaveFile = QPushButton(self.MainUI)
        self.SaveFile.setObjectName(u"SaveFile")
        self.SaveFile.setGeometry(QRect(100, 600, 75, 24))
        self.LoadFile = QPushButton(self.MainUI)
        self.LoadFile.setObjectName(u"LoadFile")
        self.LoadFile.setGeometry(QRect(10, 600, 75, 24))
        self.Exit = QPushButton(self.MainUI)
        self.Exit.setObjectName(u"Exit")
        self.Exit.setGeometry(QRect(380, 600, 75, 24))
        EnemyEditor.setCentralWidget(self.MainUI)
        QWidget.setTabOrder(self.tabWidget, self.EnemiesList)
        QWidget.setTabOrder(self.EnemiesList, self.EnemyAddButton)
        QWidget.setTabOrder(self.EnemyAddButton, self.EnemyDeleteButton)
        QWidget.setTabOrder(self.EnemyDeleteButton, self.EnemyKeyVal)
        QWidget.setTabOrder(self.EnemyKeyVal, self.EnemyIDVal)
        QWidget.setTabOrder(self.EnemyIDVal, self.EnemyNameVal)
        QWidget.setTabOrder(self.EnemyNameVal, self.EnemyBIDVal)
        QWidget.setTabOrder(self.EnemyBIDVal, self.EnemyGIDVal)
        QWidget.setTabOrder(self.EnemyGIDVal, self.EnemyHPVal)
        QWidget.setTabOrder(self.EnemyHPVal, self.EnemySTRVal)
        QWidget.setTabOrder(self.EnemySTRVal, self.EnemySPDVal)
        QWidget.setTabOrder(self.EnemySPDVal, self.EnemyATKVal)
        QWidget.setTabOrder(self.EnemyATKVal, self.EnemyDEFVal)
        QWidget.setTabOrder(self.EnemyDEFVal, self.EnemyAPTVal)
        QWidget.setTabOrder(self.EnemyAPTVal, self.EnemyFATKVal)
        QWidget.setTabOrder(self.EnemyFATKVal, self.EnemyFDEFVal)
        QWidget.setTabOrder(self.EnemyFDEFVal, self.EnemyIATKVal)
        QWidget.setTabOrder(self.EnemyIATKVal, self.EnemyIDEFVal)
        QWidget.setTabOrder(self.EnemyIDEFVal, self.EnemyLATKVal)
        QWidget.setTabOrder(self.EnemyLATKVal, self.EnemyLDEFVal)
        QWidget.setTabOrder(self.EnemyLDEFVal, self.EnemyExpVal)
        QWidget.setTabOrder(self.EnemyExpVal, self.EnemyLevelVal)
        QWidget.setTabOrder(self.EnemyLevelVal, self.EnemyILevelVal)
        QWidget.setTabOrder(self.EnemyILevelVal, self.EnemyRarityVal)
        QWidget.setTabOrder(self.EnemyRarityVal, self.EnemyMaxItemsVal)
        QWidget.setTabOrder(self.EnemyMaxItemsVal, self.LoadFile)
        QWidget.setTabOrder(self.LoadFile, self.SaveFile)
        QWidget.setTabOrder(self.SaveFile, self.Exit)
        QWidget.setTabOrder(self.Exit, self.SimEnemiesList)
        QWidget.setTabOrder(self.SimEnemiesList, self.PlayerHPVal)
        QWidget.setTabOrder(self.PlayerHPVal, self.PlayerMaxHPVal)
        QWidget.setTabOrder(self.PlayerMaxHPVal, self.PlayerSTRVal)
        QWidget.setTabOrder(self.PlayerSTRVal, self.PlayerCONVal)
        QWidget.setTabOrder(self.PlayerCONVal, self.PlayerDEXVal)
        QWidget.setTabOrder(self.PlayerDEXVal, self.PlayerATKVal)
        QWidget.setTabOrder(self.PlayerATKVal, self.PlayerDEFVal)
        QWidget.setTabOrder(self.PlayerDEFVal, self.PlayerSPDVal)
        QWidget.setTabOrder(self.PlayerSPDVal, self.PlayerFATKVal)
        QWidget.setTabOrder(self.PlayerFATKVal, self.PlayerFDEFVal)
        QWidget.setTabOrder(self.PlayerFDEFVal, self.PlayerIATKVal)
        QWidget.setTabOrder(self.PlayerIATKVal, self.PlayerIDEFVal)
        QWidget.setTabOrder(self.PlayerIDEFVal, self.PlayerLATKVal)
        QWidget.setTabOrder(self.PlayerLATKVal, self.PlayerLDEFVal)
        QWidget.setTabOrder(self.PlayerLDEFVal, self.PlayerFDMGVal)
        QWidget.setTabOrder(self.PlayerFDMGVal, self.PlayerIDMGVal)
        QWidget.setTabOrder(self.PlayerIDMGVal, self.PlayerLDMGVal)
        QWidget.setTabOrder(self.PlayerLDMGVal, self.PlayerBlockVal)
        QWidget.setTabOrder(self.PlayerBlockVal, self.PlayerAPTVal)
        QWidget.setTabOrder(self.PlayerAPTVal, self.PlayerResetHP)
        QWidget.setTabOrder(self.PlayerResetHP, self.PlayerAttack)
        QWidget.setTabOrder(self.PlayerAttack, self.CombatLogOutput)

        self.retranslateUi(EnemyEditor)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(EnemyEditor)
    # setupUi

    def retranslateUi(self, EnemyEditor):
        EnemyEditor.setWindowTitle(QCoreApplication.translate("EnemyEditor", u"SLAC Enemy Tool", None))
        self.EnemyStats.setTitle(QCoreApplication.translate("EnemyEditor", u"Stats", None))
        self.EnemyID.setText(QCoreApplication.translate("EnemyEditor", u"ID", None))
        self.EnemyName.setText(QCoreApplication.translate("EnemyEditor", u"Name", None))
        self.EnemyGID.setText(QCoreApplication.translate("EnemyEditor", u"GID", None))
        self.EnemyBID.setText(QCoreApplication.translate("EnemyEditor", u"BID", None))
        self.EnemyHP.setText(QCoreApplication.translate("EnemyEditor", u"HP", None))
        self.EnemySTR.setText(QCoreApplication.translate("EnemyEditor", u"STR", None))
        self.EnemySPD.setText(QCoreApplication.translate("EnemyEditor", u"SPD", None))
        self.EnemyATK.setText(QCoreApplication.translate("EnemyEditor", u"ATK", None))
        self.EnemyDEF.setText(QCoreApplication.translate("EnemyEditor", u"DEF", None))
        self.EnemyAPT.setText(QCoreApplication.translate("EnemyEditor", u"APT", None))
        self.EnemyFATK.setText(QCoreApplication.translate("EnemyEditor", u"FATK", None))
        self.EnemyIATK.setText(QCoreApplication.translate("EnemyEditor", u"IATK", None))
        self.EnemyLATK.setText(QCoreApplication.translate("EnemyEditor", u"LATK", None))
        self.EnemyIDEF.setText(QCoreApplication.translate("EnemyEditor", u"IDEF", None))
        self.EnemyLDEF.setText(QCoreApplication.translate("EnemyEditor", u"LDEF", None))
        self.EnemyFDEF.setText(QCoreApplication.translate("EnemyEditor", u"FDEF", None))
        self.EnemyLevel.setText(QCoreApplication.translate("EnemyEditor", u"ELevel", None))
        self.EnemyRarity.setText(QCoreApplication.translate("EnemyEditor", u"Rarity", None))
        self.EnemyExp.setText(QCoreApplication.translate("EnemyEditor", u"EXP", None))
        self.EnemyILevel.setText(QCoreApplication.translate("EnemyEditor", u"ILevel", None))
        self.EnemyMaxItemsVal.setText("")
        self.EnemyMaxItems.setText(QCoreApplication.translate("EnemyEditor", u"Max Items", None))
        self.EnemyKey.setText(QCoreApplication.translate("EnemyEditor", u"Key", None))
        self.EnemyBitmap.setText("")
        self.EnemyAddButton.setText(QCoreApplication.translate("EnemyEditor", u"Add", None))
        self.EnemyDeleteButton.setText(QCoreApplication.translate("EnemyEditor", u"Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EnemyEdit), QCoreApplication.translate("EnemyEditor", u"Enemy Editor", None))
        self.PlayerStats.setTitle(QCoreApplication.translate("EnemyEditor", u"Player Stats", None))
        self.PlayerHP.setText(QCoreApplication.translate("EnemyEditor", u"HP", None))
        self.PlayerMaxHP.setText(QCoreApplication.translate("EnemyEditor", u"Max HP", None))
        self.PlayerSTR.setText(QCoreApplication.translate("EnemyEditor", u"STR", None))
        self.PlayerCON.setText(QCoreApplication.translate("EnemyEditor", u"CON", None))
        self.PlayerDEX.setText(QCoreApplication.translate("EnemyEditor", u"DEX", None))
        self.PlayerATK.setText(QCoreApplication.translate("EnemyEditor", u"ATK", None))
        self.PlayerDEF.setText(QCoreApplication.translate("EnemyEditor", u"DEF", None))
        self.PlayerSPD.setText(QCoreApplication.translate("EnemyEditor", u"SPD", None))
        self.PlayerLATK.setText(QCoreApplication.translate("EnemyEditor", u"LATK", None))
        self.PlayerLDEF.setText(QCoreApplication.translate("EnemyEditor", u"LDEF", None))
        self.PlayerIDEF.setText(QCoreApplication.translate("EnemyEditor", u"IDEF", None))
        self.PlayerFDEF.setText(QCoreApplication.translate("EnemyEditor", u"FDEF", None))
        self.PlayerFATK.setText(QCoreApplication.translate("EnemyEditor", u"FATK", None))
        self.PlayerIATK.setText(QCoreApplication.translate("EnemyEditor", u"IATK", None))
        self.PlayerBlock.setText(QCoreApplication.translate("EnemyEditor", u"Block", None))
        self.PlayerFDMG.setText(QCoreApplication.translate("EnemyEditor", u"FDMG", None))
        self.PlayerIDMG.setText(QCoreApplication.translate("EnemyEditor", u"IDMG", None))
        self.PlayerLDMG.setText(QCoreApplication.translate("EnemyEditor", u"LDMG", None))
        self.PlayerAPT.setText(QCoreApplication.translate("EnemyEditor", u"APT", None))
        self.CombatLog.setTitle(QCoreApplication.translate("EnemyEditor", u"Combat Log", None))
        self.PlayerAttack.setText(QCoreApplication.translate("EnemyEditor", u"Attack!", None))
        self.PlayerResetHP.setText(QCoreApplication.translate("EnemyEditor", u"Reset HP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BattleSimulator), QCoreApplication.translate("EnemyEditor", u"Battle Simulator", None))
        self.SaveFile.setText(QCoreApplication.translate("EnemyEditor", u"Save File", None))
        self.LoadFile.setText(QCoreApplication.translate("EnemyEditor", u"Load File", None))
        self.Exit.setText(QCoreApplication.translate("EnemyEditor", u"Exit", None))
    # retranslateUi

